--liquibase formatted sql
--changeset husrav:insof-test

CREATE TABLE mouse_positions
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x  INT,
    y  INT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);