--liquibase formatted sql
--changeset husrav:insof-test

CREATE TABLE users
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    password    VARCHAR(100) NOT NULL
);